---
- hosts: my_servers
  become: true
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false

    - name: Create user 'testing'
      ansible.builtin.user:
        name: testing
        state: present



   
